#!/bin/bash
#
#	 d8b   8888888b. 888
#	 Y8P   888   Y88b888
#	       888    888888
#	 888   888   d88P888 .d88b. 888  888
#	 888   8888888P" 888d8P  Y8b`Y8bd8P' 
#	 888   888       88888888888  X88K 
#	 888   888       888Y8b.    .d8""8b. 
#	 888   888       888 "Y8888 888  888   
#			
# @author Myles McNamara
# @date 7.17.2013
# @version 1.0
# @source https://github.com/tripflex/gitlab-recipes/
# ----------------------------------------------------------------------
# @usage ./iplex plexmediaserver.deb
# ----------------------------------------------------------------------
# @copyright Copyright (C) 2013 Myles McNamara
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] || [[ $1 == -* ]]; then
 	echo "Usage: $0 plexmediaserver.deb" >&2
 	exit
fi

# Start install of Plex Media Server
dpkg -i $1

# Check if file exists already and has size greater than 0
if [ -s '/etc/init.d/plexmediaserver' ]; then
	mv /etc/init.d/plexmediaserver /etc/init.d/plexmediaserver.old
fi

# Download init.d script from GitHub master branch
curl -o '/etc/init.d/plexmediaserver' 'https://raw.github.com/tripflex/iPlex/master/etc/init.d/plexmediaserver'